version: '3'
services:
  wordpress:
    image: galileo/wordpress-fpm
    build:
      context: ./wordpress


    #environment:
    #  - WP_HOME=https://mysite.com
    #  - WP_SITEURL=https://mysite.com
    volumes:
      - ./data:/var/www/html
  http:
    image: galileo/wordpress-nginx
    build:
      context: ./nginx
    volumes_from:
      - wordpress
    #volumes:
    #  - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"

