# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - docker compose build

  publish:
    cmds:
      - task: build
      - docker tag galileo/wordpress-fpm docker.csgalileo.org/galileo/wordpress-fpm:6.0.2
      - docker push docker.csgalileo.org/galileo/wordpress-fpm:6.0.2
      - docker tag galileo/wordpress-nginx docker.csgalileo.org/galileo/wordpress-nginx:latest
      - docker push docker.csgalileo.org/galileo/wordpress-nginx:latest
