version: '3'
services:
  wordpress:
    image: galileo/wordpress-lite
    build:
      context: .
    volumes:
      - ./data:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8081:80"

